"""Added Creation DateTimes for Purchases and Tickets

Revision ID: 25a8d53d00f9
Revises: 70df7fdefc
Create Date: 2014-12-02 16:25:29.181154

"""

# revision identifiers, used by Alembic.
revision = '25a8d53d00f9'
down_revision = '70df7fdefc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.add_column('purchases', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'date')
    op.drop_column('purchases', 'date')
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    ### end Alembic commands ###
