"""empty message

Revision ID: 4fc16f75ced8
Revises: 15411c2d9318
Create Date: 2015-02-26 20:30:57.595509

"""

# revision identifiers, used by Alembic.
revision = '4fc16f75ced8'
down_revision = '15411c2d9318'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('draft', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'draft')
    ### end Alembic commands ###
