#!/usr/bin/env python
from app import manager
from app import db
from app.models import Setting, User


@manager.command
def setting(name=None, value=None):
    if name:
        setting = Setting.query.filter_by(name=name).first()
        if value:
            if setting:
                setting.value = value
                db.session.merge(setting)
            else:
                setting = Setting(name=name, value=value)
                db.session.add
            db.session.flush()
            db.session.commit()
        else:
            print '%s = %s' % (setting.name, setting.value)
    else:
        for setting in Setting.query.all():
            print setting.name


@manager.command
def create_admin(email):
    user = User(email=email)
    user.admin = True
    db.session.add(user)
    db.session.flush()
    db.session.commit()


@manager.command
def populate():
    pass


if __name__ == '__main__':
    manager.run()